### ISSUE TITLE
"MultiPoint" object not iterable

### ISSUE THREAD

**Issue by S-Schefer** [XDynames/SAI-app#12]
Hi

I am using the CPU mode. When I was trying out SAI on one of your example images from GitHub, I got this error:

2023-02-10 15:16:48.381 Uncaught app exception
Traceback (most recent call last):
  File "/home/{user}/.local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/{user}/SAI-app/main.py", line 38, in <module>
    main()
  File "/home/{user}/SAI-app/main.py", line 16, in main
    maybe_do_inference()
  File "/home/{user}/SAI-app/app/inference.py", line 58, in maybe_do_inference
    maybe_do_single_image_inference()
  File "/home/{user}/SAI-app/app/inference.py", line 71, in maybe_do_single_image_inference
    predictions, valid_indices = predictions_to_list_of_dictionaries(
  File "/home/{user}/SAI-app/app/inference.py", line 259, in predictions_to_list_of_dictionaries
    predictions = [
  File "/home/{user}/SAI-app/app/inference.py", line 260, in <listcomp>
    predictions_to_dictionary(i, predictions, n_stoma, valid_indices)
  File "/home/{user}/SAI-app/app/inference.py", line 281, in predictions_to_dictionary
    pred_CD = find_CD(pred_polygon, pred_AB)
  File "/home/{user}/SAI-app/app/inference.py", line 401, in find_CD
    intersections = select_longest_line(intersections)
  File "/home/{user}/SAI-app/app/inference.py", line 414, in select_longest_line
    for i, point_1 in enumerate(multipoint):
TypeError: 'MultiPoint' object is not iterable

Cheers

**Comment by XDynames** [comment]
Are you using sample images downloaded from the links in the Readme? Those are high resolution original images

If you’re saving the ones displayed from the webpage they’ll be low resolution previews

I should make this failure more graceful currently this happens when one or fewer detections are made in an image. I’ll try to take a deeper look this week

**Comment by S-Schefer** [comment]
I'm using the images downloaded from the links.

**Comment by S-Schefer** [comment]
Additional Info:

Camera Calibration: 4,0000
IST: 0.5

Works with most of the images but some cause the error: one is 5Mar7

**Comment by XDynames** [comment]
Thanks for the additional information 
I’ll take a look shortly

**Comment by XDynames** [comment]
I have pushed a change to master that should fix this issue

Looks like it was the new Shapely API rearing its head again

Let me know how it goes for you and thanks for helping us make SAI better

**Comment by S-Schefer** [comment]
I no longer get the error.  So I will close this issue.
But the program still has difficulties detecting the stomata in 5Mar7.

Thank you very much

**Comment by XDynames** [comment]
Do you mind send me the visualised detections your getting for 5Mar7?

**Comment by S-Schefer** [comment]
I am so sorry. I forgot to switch from Arabidopsis to Barley for my trail run after you fixed the error. With Barley it works fine.

Again thank you very much for your help an sorry for the stupid mistake.

**Comment by XDynames** [comment]
Awesome!
